package com.tradewise.marketdata.model;

/**
 * Where a quote came from. Exposed to the client so the UI can label prices
 * honestly — the whole point of this milestone was that simulated prices were
 * indistinguishable from real ones.
 */
public enum DataSource {
    /** Real closing data from the upstream provider. */
    LIVE,
    /** Generated by the deterministic simulator (no API key, budget spent, or upstream down). */
    SIMULATED
}
