package com.tradewise.auth;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.tradewise.auth.dto.AuthResponse;
import com.tradewise.auth.dto.LoginRequest;
import com.tradewise.auth.dto.RegisterRequest;
import com.tradewise.exception.ApiException;
import com.tradewise.exception.ErrorCode;
import com.tradewise.security.JwtService;
import com.tradewise.user.User;
import com.tradewise.user.UserService;
import com.tradewise.wallet.WalletService;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.password.PasswordEncoder;

@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    @Mock
    private UserService userService;
    @Mock
    private WalletService walletService;
    @Mock
    private JwtService jwtService;
    @Mock
    private PasswordEncoder passwordEncoder;

    private AuthService authService;

    @BeforeEach
    void setUp() {
        authService = new AuthService(userService, walletService, jwtService, passwordEncoder);
    }

    private User stubUser(UUID id, String email) {
        User user = User.builder().email(email).passwordHash("$2a$12$hash").fullName("Test User").build();
        // id is generated by persistence; reflection keeps the entity free of test-only setters
        try {
            var idField = User.class.getDeclaredField("id");
            idField.setAccessible(true);
            idField.set(user, id);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
        return user;
    }

    @Test
    @DisplayName("registration normalizes the email, creates user and wallet, and returns a token")
    void registerCreatesUserAndWallet() {
        UUID userId = UUID.randomUUID();
        User saved = stubUser(userId, "new@example.com");
        when(userService.findByEmail("new@example.com")).thenReturn(Optional.empty());
        when(passwordEncoder.encode("passw0rd123")).thenReturn("$2a$12$encoded");
        when(userService.createUser("new@example.com", "$2a$12$encoded", "New User")).thenReturn(saved);
        when(jwtService.issueToken(userId, "new@example.com")).thenReturn("token");
        when(jwtService.expirySeconds()).thenReturn(3600L);

        AuthResponse response = authService.register(
                new RegisterRequest("  NEW@Example.COM ", "passw0rd123", " New User "));

        assertThat(response.accessToken()).isEqualTo("token");
        assertThat(response.user().email()).isEqualTo("new@example.com");
        verify(walletService).openWallet(userId);
    }

    @Test
    @DisplayName("registration with an existing email fails with EMAIL_ALREADY_REGISTERED")
    void registerDuplicateEmailFails() {
        when(userService.findByEmail("taken@example.com"))
                .thenReturn(Optional.of(stubUser(UUID.randomUUID(), "taken@example.com")));

        assertThatThrownBy(() -> authService.register(
                new RegisterRequest("taken@example.com", "passw0rd123", "Someone")))
                .isInstanceOfSatisfying(ApiException.class,
                        exception -> assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.EMAIL_ALREADY_REGISTERED));

        verify(walletService, never()).openWallet(any());
    }

    @Test
    @DisplayName("losing a concurrent-registration race maps the constraint violation to EMAIL_ALREADY_REGISTERED")
    void registerRaceLoserGetsConflict() {
        when(userService.findByEmail("race@example.com")).thenReturn(Optional.empty());
        when(passwordEncoder.encode(anyString())).thenReturn("$2a$12$encoded");
        when(userService.createUser(eq("race@example.com"), anyString(), anyString()))
                .thenThrow(new DataIntegrityViolationException("ux_users_email_lower"));

        assertThatThrownBy(() -> authService.register(
                new RegisterRequest("race@example.com", "passw0rd123", "Racer")))
                .isInstanceOfSatisfying(ApiException.class,
                        exception -> assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.EMAIL_ALREADY_REGISTERED));
    }

    @Test
    @DisplayName("unknown email and wrong password produce the same error, and BCrypt runs either way")
    void loginFailuresAreIndistinguishable() {
        when(userService.findByEmail("nobody@example.com")).thenReturn(Optional.empty());
        when(passwordEncoder.matches(anyString(), anyString())).thenReturn(false);

        assertThatThrownBy(() -> authService.login(new LoginRequest("nobody@example.com", "whatever1")))
                .isInstanceOfSatisfying(ApiException.class,
                        exception -> assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.INVALID_CREDENTIALS));

        // The timing defense: even for an unknown email, a BCrypt comparison happened.
        verify(passwordEncoder).matches(eq("whatever1"), anyString());

        User user = stubUser(UUID.randomUUID(), "known@example.com");
        when(userService.findByEmail("known@example.com")).thenReturn(Optional.of(user));

        assertThatThrownBy(() -> authService.login(new LoginRequest("known@example.com", "wrongpass1")))
                .isInstanceOfSatisfying(ApiException.class,
                        exception -> assertThat(exception.getErrorCode()).isEqualTo(ErrorCode.INVALID_CREDENTIALS));
    }

    @Test
    @DisplayName("valid credentials produce a bearer token")
    void loginSucceeds() {
        UUID userId = UUID.randomUUID();
        User user = stubUser(userId, "known@example.com");
        when(userService.findByEmail("known@example.com")).thenReturn(Optional.of(user));
        when(passwordEncoder.matches("passw0rd123", "$2a$12$hash")).thenReturn(true);
        when(jwtService.issueToken(userId, "known@example.com")).thenReturn("token");
        when(jwtService.expirySeconds()).thenReturn(3600L);

        AuthResponse response = authService.login(new LoginRequest("known@example.com", "passw0rd123"));

        assertThat(response.accessToken()).isEqualTo("token");
        assertThat(response.tokenType()).isEqualTo("Bearer");
    }
}
