import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { DatePipe } from '@angular/common';
import { DataSource } from '../core/api-types';

/**
 * States plainly where a price came from.
 *
 * This exists because simulated prices were previously indistinguishable from real
 * ones — a stock could show a number nowhere near its actual market price with
 * nothing on screen to say so. It also explains why a real price does not move:
 * the free upstream tier is end-of-day, so the figure is a closing price for a
 * stated trading day, not a live tick.
 */
@Component({
  selector: 'app-data-source-chip',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DatePipe],
  template: `
    @if (source() === 'LIVE') {
      <span class="chip chip-accent" [title]="tooltip()">
        REAL CLOSE · {{ tradingDay() | date: 'dd MMM' }}
      </span>
    } @else {
      <span class="chip chip-warn" [title]="tooltip()">SIMULATED</span>
    }
  `,
  styles: `:host { display: inline-flex; }`,
})
export class DataSourceChip {
  readonly source = input.required<DataSource>();
  readonly tradingDay = input.required<string>();

  protected readonly tooltip = computed(() =>
    this.source() === 'LIVE'
      ? 'Real closing price from the market data provider. The free tier is end-of-day, '
        + 'so this is the official close for the stated trading day, not a live tick.'
      : 'No live data for this symbol (no API key, daily request budget spent, or provider '
        + 'unavailable), so the price is generated by the built-in simulator. It is not a real price.',
  );
}
